import { ProductUdfs } from "./ProductUdfs";
import { ProductTags } from "./ProductTags";
import { MeasurementDetails } from "./MeasurementDetails";
import { Supplier } from "./Supplier";
import { TaxGroup } from "./TaxGroup";

export interface Product {
  Id: number;
  Name: string;
  Description: string;
  CostPrice: number;
  IsCostPriceIncTax: boolean;
  SalePrice: number;
  IsSalePriceIncTax: boolean;
  EatOutPrice: number;
  IsEatOutPriceIncTax: boolean;
  CategoryId: number;
  Barcode: string;
  SalePriceTaxGroupId: number;
  EatOutPriceTaxGroupId: number;
  CostPriceTaxGroupId: number;
  BrandId: number;
  SupplierId: number;
  PopupNoteId: number;
  UnitOfSale: number;
  VolumeOfSale: number;
  VariantGroupId: number;
  MultipleChoiceNoteId: number;
  Size: string;
  Sku: string;
  SellOnWeb: boolean;
  SellOnTill: boolean;
  OrderCode: string;
  SortPosition: number;
  RrPrice: number;
  ProductType: number;
  TareWeight: number;
  ArticleCode: string;
  IsTaxExemptable: boolean;
  ReferenceCode: string;
  IsVariablePrice: boolean;
  ColourId: number;
  MeasurementDetails: MeasurementDetails;
  Supplier: Supplier;
  SalePriceTaxGroup: TaxGroup;
  EatOutPriceTaxGroup: TaxGroup;
  CostPriceTaxGroup: TaxGroup;
  ProductTags: ProductTags[];
  ProductUdfs: ProductUdfs[];
}
